# Docker compose to run the php application
version: '3.7'

services:
  thinkidownloader:
    image: sumeetweb/thinki-php:latest
    container_name: ThinkiDownloader
    volumes:
      - .:/app
    working_dir: /app
    command: php thinkidownloader3.php ${COURSE_LINK}
    environment:
      - COURSE_LINK=${COURSE_LINK}
      - CLIENT_DATE=${CLIENT_DATE}
      - COOKIE_DATA=${COOKIE_DATA}
      - VIDEO_DOWNLOAD_QUALITY=${VIDEO_DOWNLOAD_QUALITY}
